service: inner

provider:
  name: aws
  runtime: java8

stage: dev
region: us-west-2

package:
  artifact: build/libs/inner-all.jar

functions:
  hello:
    handler: jp.tukiyo.serverless.oukaApi.inner.handler.TestHandler
    events:
      - http:
          path: hoge/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
